# Generated by Django 4.0.2 on 2022-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
