# Generated by Django 4.0.2 on 2022-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrelation',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
