# Generated by Django 4.0.2 on 2022-02-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(db_index=True, max_length=20, unique=True)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'config_info',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('remote', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('remote_commit', models.CharField(blank=True, max_length=255, null=True)),
                ('local_commit', models.CharField(blank=True, max_length=255, null=True)),
                ('modified', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(blank=True, to='configuration.PackageVersion')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='configuration.package')),
            ],
            options={
                'db_table': 'package_version',
            },
        ),
        migrations.CreateModel(
            name='ConfigDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.packageversion')),
            ],
            options={
                'db_table': 'config_document',
            },
        ),
        migrations.AddConstraint(
            model_name='packageversion',
            constraint=models.UniqueConstraint(fields=('package_id', 'version'), name='package_version_unique_code_version'),
        ),
        migrations.AddConstraint(
            model_name='configdocument',
            constraint=models.UniqueConstraint(fields=('package_version_id', 'document_type', 'code'), name='config_document_unique_key'),
        ),
    ]
